package com.example.soccergamesfinder.services

import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.*
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.io.IOException
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Interface for interacting with a GPT-based API service.
 */
interface GptService {
    /**
     * Sends a prompt to the GPT model and returns the generated response.
     *
     * @param prompt The user input or question to send.
     * @return The response generated by the GPT model.
     * @throws IOException if the request fails or the response is invalid.
     */
    suspend fun sendPrompt(prompt: String): String
}

/**
 * Implementation of [GptService] using the OpenRouter API to communicate with GPT.
 *
 * @property apiKey The API key used for authenticating with the OpenRouter service.
 */
@Singleton
class GptServiceImpl @Inject constructor(
    private val apiKey: String
) : GptService {

    /** HTTP client for making network requests. */
    private val client = OkHttpClient()

    /**
     * Sends the given prompt to OpenRouter and retrieves a GPT-generated response.
     *
     * @param prompt The text to send to the GPT model.
     * @return The generated response content.
     * @throws IOException if the response is invalid or the request fails.
     */
    override suspend fun sendPrompt(prompt: String): String = withContext(Dispatchers.IO) {
        val url = "https://openrouter.ai/api/v1/chat/completions"
        val mediaType = "application/json".toMediaType()

        // Build the request body using the OpenRouter format
        val requestBody = JSONObject().apply {
            put("model", "openai/gpt-3.5-turbo") // Can be customized
            put("messages", JSONArray().apply {
                put(JSONObject().apply {
                    put("role", "user")
                    put("content", prompt)
                })
            })
        }.toString().toRequestBody(mediaType)

        // Construct the HTTP request with headers
        val request = Request.Builder()
            .url(url)
            .post(requestBody)
            .addHeader("Content-Type", "application/json")
            .addHeader("Authorization", "Bearer $apiKey") // Secure API key
            .addHeader("HTTP-Referer", "https://yourapp.com") // Required by OpenRouter
            .build()

        try {
            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    Log.e("GPT", "❌ Failed to contact GPT: $response")
                    throw IOException("Unexpected HTTP response: $response")
                }

                val body = response.body?.string() ?: throw IOException("Empty response body")
                Log.d("GPT", "🧠 GPT Response Body: $body")

                val json = JSONObject(body)

                if (!json.has("choices")) {
                    Log.e("GPT", "❌ Missing 'choices' field in response: $json")
                    throw IOException("Missing 'choices' in response")
                }

                val choices = json.getJSONArray("choices")
                val message = choices.getJSONObject(0).getJSONObject("message")
                return@withContext message.getString("content")
            }
        } catch (e: Exception) {
            Log.e("GPT", "Exception during GPT call: ${e.message}", e)
            throw e
        }
    }
}
